### PR TITLE
Fix flex scanner push-back overflow issue

### LINKED ISSUE #3215: flex scanner push-back overflow
### What reproduces the bug? Provide code if possible.

```bpftrace
#include <linux/watch_queue.h>

tracepoint:syscalls:sys_enter_ioctl
/args->cmd == IOC_WATCH_QUEUE_SET_FILTER/
{
    @ioctl_count[pid]++;
}

tracepoint:syscalls:sys_enter_socket
{
    @socket_count[pid]++;
}

tracepoint:syscalls:sys_enter_pipe2
{
    @pipe2_count[pid]++;
}

tracepoint:syscalls:sys_enter_msgget
{
    @msgget_count[pid]++;
}

tracepoint:syscalls:sys_enter_msgsnd
{
    @msgsnd_count[pid]++;
}

tracepoint:syscalls:sys_enter_msgrcv
{
    @msgrcv_count[pid]++;
}

tracepoint:syscalls:sys_enter_read
{
    @read_count[pid]++;
}

tracepoint:syscalls:sys_enter_write
{
    @write_count[pid]++;
}

tracepoint:syscalls:sys_enter_close
{
    @close_count[pid]++;
}

tracepoint:syscalls:sys_enter_execve
{
    delete(@ioctl_count[pid]);
    delete(@socket_count[pid]);
    delete(@pipe2_count[pid]);
    delete(@msgget_count[pid]);
    delete(@msgsnd_count[pid]);
    delete(@msgrcv_count[pid]);
    delete(@read_count[pid]);
    delete(@write_count[pid]);
    delete(@close_count[pid]);
}

```

```
❯ sudo bpftrace test.bt
flex scanner push-back overflow
```

### `bpftrace --info` output

```
System
  OS: Linux 6.5.13-7-MANJARO #1 SMP PREEMPT_DYNAMIC Wed Dec 20 07:15:58 UTC 2023
  Arch: x86_64

Build
  version: v0.20.4
  LLVM: 17.0.6
  unsafe probe: no
  bfd: yes
  libdw (DWARF support): yes

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: yes
  probe_read_user_str: yes
  probe_read_kernel: yes
  probe_read_kernel_str: yes
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: yes
  get_boot_ns: yes
  dpath: yes
  skboutput: yes
  get_tai_ns: yes
  get_func_ip: yes
  jiffies64: yes

Kernel features
  Instruction limit: 1000000
  Loop support: yes
  btf: yes
  module btf: yes
  map batch: yes
  uprobe refcount (depends on Build:bcc bpf_attach_uprobe refcount): yes

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes
  ringbuf: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: yes
  kprobe_multi: yes
  uprobe_multi: no
  raw_tp_special: yes
  iter: yes

```

### PR DESCRIPTION
**Pull request by wokron**
Fixes #3215 

This issue was caused by two factors:
1. Unlike `yy_create_buffer()`, the buffer created by calling `yy_scan_string()` was only the size of the string, not `YY_BUF_SIZE`, which makes it easy to encounter buffer overflow.
2. During macro processing, `YY_BUF_SIZE` was assumed to be the **remaining** buffer size, leading to calls to `unput()` even when the buffer was full. (#2313)

I defined the `yy_scan_string_with_size()` function to create a buffer of a specified size (`MAX_BUF_SIZE`). And defined the `yy_is_buffer_full()` function to check if the buffer is full, preventing calls to `unput()` when the buffer is already full.

##### Checklist

- [ ] Language changes are updated in `man/adoc/bpftrace.adoc`
- [ ] User-visible and non-trivial changes updated in `CHANGELOG.md`
- [x] The new behaviour is covered by tests

### CODE REVIEW

File: src/driver.cpp [hunk 1]
```diff
@@ -7,8 +7,12 @@
 
 struct yy_buffer_state;
 
-extern struct yy_buffer_state *yy_scan_string(const char *yy_str,
-                                              yyscan_t yyscanner);
+#ifndef YY_BUF_SIZE
+#define YY_BUF_SIZE 16384
```
Comment (jordalgo) [inline src/driver.cpp:11]: Isn't this the default size? When is the case that it's undefined?

File: src/lexer.l [hunk 2]
```diff
@@ -267,18 +270,20 @@ struct|union|enum       {
...
-                                  driver.error(loc, std::string("Macro recursion limit reached: ")
-                                                    + original_yytext + ", " + original_s);
+                                if (unput_count >= 1000 || yy_is_buffer_full(yyg)) {
+                                  if (unput_count >= 1000)
+                                    driver.error(loc, std::string("Macro recursion limit reached: ")
+                                            + original_yytext + ", " + original_s);
+                                  else
+                                    driver.error(loc, std::string("Buffer overflow while expanding macro: ")
+                                          + original_yytext + ", " + original_s);
                                   yyterminate();
```
Comment (jordalgo) [inline src/lexer.l:283]: I think it reads better this way:
```suggestion
                                if (yy_is_buffer_full(yyg)) {
                                  driver.error(loc, std::string("Buffer overflow while expanding macro: ")
                                          + original_yytext + ", " + original_s);
                                    yyterminate();
                                } else if (unput_count >= 1000) {
                                  driver.error(loc, std::string("Macro recursion limit reached: ")
                                            + original_yytext + ", " + original_s);
                                  yyterminate();
                                }
                                    
                                 
```

**Review by jordalgo — CHANGES_REQUESTED** [review]
Thanks for working on this! I see in the issue that @ajor has a minimal repo. Do you mind adding a test that failed before and now passes with this change?

File: src/driver.cpp (hunk 1 above)
Comment (wokron) [reply src/driver.cpp:11]: Since we only generated lex.yy.cc, we cannot include the `YY_BUF_SIZE` defined within it (which is a macro). Therefore, `YY_BUF_SIZE` is actually always undefined in driver.cpp. So I copied the definition of `YY_BUF_SIZE` here. Adding `#ifndef` allows users to configure the size of `YY_BUF_SIZE`, just like in lex.yy.cc.

Comment (wokron) [reply src/driver.cpp:11]: In fact, the `YY_BUF_SIZE` here does not need to be consistent with the `YY_BUF_SIZE` in flex, so perhaps we can change the name. Considering that the length of the source string may be longer than `YY_BUF_SIZE`, I set the buffer size to `max(source.size(), YY_BUF_SIZE)` in my recent changes. Perhaps we can rename `YY_BUF_SIZE` here to `MIN_YY_BUF_SIZE`?

Comment (jordalgo) [reply src/driver.cpp:11]: > Perhaps we can rename YY_BUF_SIZE here to MIN_YY_BUF_SIZE?

Yeah that makes sense to me. Thanks for explaining

File: tests/parser.cpp [hunk 3]
```diff
@@ -2872,4 +2872,36 @@ BEGIN { $x: int8 = 1; }
 )");
 }
 
+TEST(Parser, macro_expansion_error)
+{
+  BPFtrace bpftrace;
+  // #define M M+1
+  bpftrace.macros_.emplace("M", "M+1");
```
Comment (jordalgo) [inline tests/parser.cpp:2879]: I know you're saving code here but can we just inline the macro in both tests?

Also is it possible to get a buffer overflow error that doesn't involve a macro that causes a recursion limit error?

Comment (wokron) [reply tests/parser.cpp:2879]: > I know you're saving code here but can we just inline the macro in both tests?

At first, I did inline the macro into the source string, but I found that the `Driver` actually ignores my macro definition because the parsing of macro definitions is actually done in the `ClangParser`. So I directly insert the macro into the `macro_` map to mock the behavior of `ClangParser`. But I agree that the macro definition should be kept in the source string.

Comment (wokron) [reply tests/parser.cpp:2879]: > Also is it possible to get a buffer overflow error that doesn't involve a macro that causes a recursion limit error?

Sure, but it only occurs when using macros from header files, just like the minimal repo in #3215. I'll change the test to this case.

Comment (jordalgo) [reply tests/parser.cpp]: > because the parsing of macro definitions is actually done in the ClangParser

Ah right. I forgot about that 😞

**Review by jordalgo — DISMISSED** [review]
LGTM. Thanks for the contribution!

File: src/driver.cpp [hunk 4]
```diff
@@ -7,8 +7,12 @@
 
 struct yy_buffer_state;
 
-extern struct yy_buffer_state *yy_scan_string(const char *yy_str,
-                                              yyscan_t yyscanner);
+#ifndef MIN_YY_BUF_SIZE
```
Comment (danobi) [inline src/driver.cpp:10]: This is not some preprocessor definition exported by flex, right? IMO better to drop the `#ifndef` - it's confusing b/c it has no users (overrides) in our codebase.

File: src/driver.cpp [hunk 5]
```diff
@@ -46,7 +50,11 @@ int Driver::parse()
   if (debug_) {
     parser.set_debug_level(1);
   }
-  yy_scan_string(Log::get().get_source().c_str(), scanner);
+  auto &source = Log::get().get_source();
+  yy_scan_string_with_size(source.c_str(),
+                           std::max(source.size(),
+                                    static_cast<size_t>(MIN_YY_BUF_SIZE)),
```
Comment (danobi) [inline src/driver.cpp:56]: If you need this to be `size_t`, maybe just declare it as `static constexpr size_t`, then? Instead of a macro

File: src/lexer.l [hunk 6]
```diff
@@ -291,3 +296,20 @@ struct|union|enum       {
...
+  b->yy_buf_size = size;
+
+  return b;
+}
+
+bool yy_is_buffer_full(struct yyguts_t *yyg) {
+  char *yy_cp = yyg->yy_c_buf_p;
+  return (yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 &&
+          YY_CURRENT_BUFFER_LVALUE->yy_n_chars == YY_CURRENT_BUFFER_LVALUE->yy_buf_size);
+}
```
Comment (danobi) [inline src/lexer.l:315]: While I'll grant this looks like it works (for now at least), it seems like this reaches way into the internals of flex. I suspect this will cause maintenance issues sooner or later, as I don't see any of these fields/types reference in the flex API.

Please consult https://westes.github.io/flex/manual/Index-of-Variables.html#Index-of-Variables and only use things in public API (or prove that it's indeed intended to be public but has no listing).

**Review by danobi — CHANGES_REQUESTED** [review]
Appreciate the fix, but the biggest issue IMO is it reaches too deep into flex internals. I think we need a way to do this with public API.

File: src/lexer.l (hunk 6 above)
Comment (wokron) [reply src/lexer.l]: You are right, I may have focused too much on the flex-generated `lex.yy.cc` file. So I reviewed the flex documentation and came up with another approach (2c44af97d7782e2b865e0504e6f7ac53436c17f2). This method is documented ([YY_INPUT, overriding](https://westes.github.io/flex/manual/Generated-Scanner.html#index-YY_005fINPUT_002c-overriding)). If it is better, I can squash this commit.

Comment (wokron) [reply src/lexer.l]: Basically, the new approach is to use a custom function to override the behavior of `YY_INPUT`, changing the input from a file to the source string we provide. In this case, the buffer size is the default `YY_BUF_SIZE`, and each read will copy up to `YY_READ_BUF_SIZE` bytes (half of the buffer size). This gives us enough space for macro expansion (larger than the macro recursion limit of 1000 bytes).

**Comment by danobi** [comment]
Sorry about the delay - this slipped off my radar. I will take a look this weekend.

File: src/lexer.l [hunk 7]
```diff
@@ -291,3 +298,15 @@ struct|union|enum       {
                                             std::string(yytext) + std::string("'")); }
 
 %%
+
+void yy_set_source_string(const std::string& s) {
+  source = s;
```
Comment (danobi) [inline src/lexer.l:303]: Technically a copy of `source` isn't necessary, right? Can read directly from driver instance? All we needed was an indirection.

File: tests/parser.cpp [hunk 8]
```diff
@@ -2872,4 +2872,23 @@ BEGIN { $x: int8 = 1; }
...
+  test_parse_failure(bpftrace,
+                     "#define M M+1\n"
+                     "BEGIN { M; }",
+                     R"(
+stdin:2:9-343: ERROR: Macro recursion limit reached: M, M+1
+BEGIN { M; }
+        ~~~~
+stdin:2:9-343: ERROR: syntax error, unexpected end of file
+BEGIN { M; }
+        ~~~~
```
Comment (danobi) [inline tests/parser.cpp:2890]: I think parser inserts this, right? So not necessary to do anything fancy.
```suggestion
  test_parse_failure("#define M M+1\n"
                     "BEGIN { M; }",
                     R"(
stdin:2:9-343: ERROR: Macro recursion limit reached: M, M+1
BEGIN { M; }
        ~~~~
stdin:2:9-343: ERROR: syntax error, unexpected end of file
BEGIN { M; }
        ~~~~
```

File: src/lexer.l [hunk 9]
```diff
@@ -291,3 +298,15 @@ struct|union|enum       {
...
+  curr = 0;
+}
+
+int yy_read_from_source(char* buf, size_t max_size) {
```
Comment (danobi) [inline src/lexer.l:307]: Would be good to document with a comment why this exists here. From your PR description, seems like the magic is:

> Unlike yy_create_buffer(), the buffer created by calling yy_scan_string() was only the size of the string, not YY_BUF_SIZE, which makes it easy to encounter buffer overflow.

So basically force flex to pessimistically allocate the buffer by not letting it see the string. Which makes sense and should work well enough for most cases. Although I wonder what happens if the input file is too big for the default buffer size...

File: tests/parser.cpp (hunk 8 above)
Comment (wokron) [reply tests/parser.cpp]: Actually, it doesn't :joy:. Macro parsing is done by `ClangParser` (https://github.com/bpftrace/bpftrace/pull/3824#discussion_r1974983783). I have added a comment to clarify this.

File: src/lexer.l [hunk 10]
```diff
@@ -19,6 +19,15 @@ static std::string buffer;
 #define yyterminate() return bpftrace::Parser::make_END(loc)
 
 using namespace bpftrace;
+
+static std::string source;
+static size_t curr;
```
[the remark this answers is not in the document]
Comment (wokron) [reply src/lexer.l]: For `source` and `curr`, it seems they cannot be moved to the `Driver` instance because `YY_INPUT` is used by an internal function of Flex (`yy_get_next_buffer`), and we have no way to pass `driver` into it. However, I have marked `source` and `curr` as `thread_local`, so this will not affect the thread safety of lexer.

As for the other global variables in `lexer.l`, I have moved them to the `Driver` class.

File: src/lexer.l (hunk 9 above)
Comment (wokron) [reply src/lexer.l]: I have added comments explaining why `YY_INPUT` is used.

> Although I wonder what happens if the input file is too big for the default buffer size...

Actually, flex can handle this. It only reads a portion of the data at a time. I have added a test case about this.

File: tests/parser.cpp (hunk 8 above)
Comment (danobi) [reply tests/parser.cpp]: Ah, got it. How about writing a new wrapper, maybe `test_macro_parse_failure(...)`? We recently overhauled the pass manager, so should be straightforward. Example of a I recently added: https://github.com/bpftrace/bpftrace/blob/882c1836aebb082995bda421cbfe30b43e5430aa/tests/deprecated.cpp#L11-L27

Reason is it'd be good to move the tests towards stricter input -> output and avoid reaching into classes to mock.

File: src/lexer.l (hunk 9 above)
Comment (danobi) [reply src/lexer.l]: Great, thanks for that!

**Review by danobi — APPROVED** [review]
thanks for working on this!

**Comment by viktormalik** [comment]
Do we want to backport this to the 0.23.x branch?

**Comment by jordalgo** [comment]
@viktormalik Good reminder. I'll put up a backport PR.
