### PR TITLE
Unify and improve ignoring of missing probes

### LINKED ISSUE #3235: Attaching to non-existing uprobes fails
#3155 broke scripts which use probes attaching to multiple uprobes when some of the target functions do not exist. Previously, we would silently ignore such attach points, now bpftrace fails with:
```
ERROR: Could not resolve symbol: ...
```

Among others, this also breaks a couple of tools (`ssllatency.bt`, `sslsnoop.bt`, `threadsnoop.bt`). CI didn't catch that since we're just parsing the tool script and do not try to attach them. This will be fixed by #3203.

While this is clearly wrong and we need to fix it, I realized that we're doing different things for uprobes and kprobes:
- for uprobes, we call `resolve_uname` and if the function doesn't exist, we silently ignore it,
- for kprobes, we always try to attach and if that fails, we issue a warning for probes with multiple attach points and continue.

I'm not sure if this is on purpose but I think that it'd be good to unify this. The options are:
1. Silently ignore non-existing attach points for both kprobes and uprobes (possibly for kfuncs, too).
2. Always issue a warning for non-existing attach points.
3. Only show warnings in verbose mode.
4. Add a CLI option or a config option to show the warnings.

All in all, any of the above options will affect the existing scripts including the tools shipped in the main repo. Either the uprobe-based tools will start showing warnings or the kprobe-based tools will stop showing them.

Personally, I'm in favor of option (3) as I find the warnings needlessly polluting the default output of tracing tools. For instance, some tools are designed in a way that there's always just one kprobe existing (b/c it was renamed in the kernel at some point) and therefore will always show the warning.

### PR DESCRIPTION
**Pull request by viktormalik**
For kprobes and uprobes, when a probe is attaching to multiple functions, we do not fail when some functions do not exist. The reason is that k(u)probes are dynamic events which regularly change between versions of kernel/binaries and we want to allow the tools to attach to all potential events while expecting some attachments to fail.

The problem is that we're not doing the ignoring consistently. For kprobes, we always show a warning if an attachment fails. For uprobes, bpftrace currently fails due to #3235 but even without the bug, we would just silently ignore the missing functions.

This PR unifies the approaches by always showing the warning. In addition, it adds a new config option `warn_missing_probes`, by default set to true, which allows to turn the warnings off. This is done for all the shipped tools.

Fixes #3235.

The first commit also fixes another attachment issue caused by a combination of kprobe_multi and progfd caching. See the commit message for details.

Note: one potential problem with ignoring missing probe warnings is that when all attach points of a probe are missing, the probe will not be attached at all without any warning. Normally, this is IMHO fine as the user must have requested to ignore warnings so he must be prepared that this may happen. The only problem is the shipped `xfsdist.bt` tool which behaves like this when the XFS module is not loaded but I wouldn't expect people to try to trace XFS calls without XFS being present on their system.

##### Checklist

- [x] Language changes are updated in `man/adoc/bpftrace.adoc`
- [x] User-visible and non-trivial changes updated in `CHANGELOG.md`
- [x] The new behaviour is covered by tests

### CODE REVIEW

**Comment by viktormalik** [comment]
There are several user-facing changes here so I ended up adding changelog entries for almost each commit (except for the second one as that fixes an unreleased bug).

File: src/attached_probe.cpp [hunk 1]
```diff
@@ -478,9 +479,16 @@ bool AttachedProbe::resolve_offset_uprobe(bool safe_mode)
...
-    if (!sym.start)
-      throw FatalUserException("Could not resolve symbol: " + probe_.path +
-                               ":" + symbol);
+    if (!sym.start) {
+      const std::string msg = "Could not resolve symbol: " + probe_.path + ":" +
+                              symbol;
+      if (error_on_missing_symbol) {
+        throw FatalUserException(msg);
+      } else {
+        LOG(WARNING) << msg << ", skipping.";
```
Comment (danobi) [inline src/attached_probe.cpp]: I think it'd be more clear to say "skipping probe." rather than just "skipping."

File: src/attached_probe.cpp [hunk 2]
```diff
@@ -478,9 +479,16 @@ bool AttachedProbe::resolve_offset_uprobe(bool safe_mode)
     sym.name = symbol;
     bcc_elf_foreach_sym(probe_.path.c_str(), sym_name_cb, &option, &sym);
 
-    if (!sym.start)
-      throw FatalUserException("Could not resolve symbol: " + probe_.path +
-                               ":" + symbol);
+    if (!sym.start) {
+      const std::string msg = "Could not resolve symbol: " + probe_.path + ":" +
+                              symbol;
```
Comment (danobi) [inline src/attached_probe.cpp:482]: Maybe add to end of message: "Cannot attach probe".

File: src/attached_probe.cpp [hunk 3]
```diff
@@ -1155,7 +1163,7 @@ void AttachedProbe::attach_uprobe(int pid, bool safe_mode)
     return;
   }
 
-  if (!resolve_offset_uprobe(safe_mode))
+  if (!resolve_offset_uprobe(safe_mode, probe_.orig_name == probe_.name))
```
Comment (danobi) [inline src/attached_probe.cpp:1173]: So basically if multiple attachpoints are on a probe, we allow missing attachpoint with a warning. But if only one attachpoint is specified, it's an error.

I think this makes sense

**Review by danobi — COMMENTED** [review]
overall lgtm

File: src/attached_probe.cpp (hunk 3 above)
Comment (viktormalik) [reply src/attached_probe.cpp:1173]: Yes, exactly. That's also how it works for kprobes.

File: src/attached_probe.cpp (hunk 1 above)
Comment (viktormalik) [reply src/attached_probe.cpp]: Good point, I updated the error/warning messages.

File: man/adoc/bpftrace.adoc [hunk 4]
```diff
@@ -2415,11 +2415,11 @@ i:s:10 {
 Count how often this function is called.
 
 Using `@=count()` is conceptually similar to `@++`.
-The difference is that the `count()` function uses a map type optimized for
```
Comment (jordalgo) [inline man/adoc/bpftrace.adoc:2418]: Thanks for removing the end space. I have the habit of adding them out of fear.

File: src/attached_probe.cpp [hunk 5]
```diff
@@ -976,6 +986,14 @@ void AttachedProbe::attach_kprobe(bool safe_mode)
     funcname = modname + ":" + funcname;
   }
 
+  // If the user requested to ignore warnings on non-existing probes and the
```
Comment (jordalgo) [inline src/attached_probe.cpp:989]: Super nit to fix our comments - turn multi line into:
```
/*
 */
```

File: tools/gethostlatency.bt [hunk 6]
```diff
@@ -19,6 +19,8 @@
  * 08-Sep-2018	Brendan Gregg	Created this.
  */
 
+config = { warn_missing_probes = 0; }
```
Comment (jordalgo) [inline tools/gethostlatency.bt:22]: I'm not saying we should change this but I guess we should be aware that this will break this script on older bpftrace versions that don't support the config syntax. I guess that's fine as people can just use an older version of the repo. -- thinking out loud.

**Review by jordalgo — APPROVED** [review]

File: tools/gethostlatency.bt (hunk 6 above)
Comment (viktormalik) [reply tools/gethostlatency.bt:22]: Yeah, since we release the scripts in lockstep with the tool, I think it's fine if the tools do not work for previous versions.

File: src/attached_probe.cpp (hunk 5 above)
Comment (viktormalik) [reply src/attached_probe.cpp:989]: We use both variants for multi-line comments (I think what I have is "C++ style") so I'd keep it as it is.

Comment (jordalgo) [reply src/attached_probe.cpp:989]: From what I understand you can use '//' for multi-line comments in C++ but I don't think that's the preferred style. I'm trying to move us to use '/**/' for multiline.

**Comment by ajor** [comment]
I'm thinking that it might be useful to add the option to have missing probes trigger an error instead of a warning too. e.g. in some kind of automated tracing system it's unlikely that people will see the warnings - an error would stop them going unnoticed.

We don't have to implement that now, but it'd be good to make the config option future-proof, e.g. maybe with options like:
```
missing_probes = "ignore"
missing_probes = "warn"
missing_probes = "error"
```

**Comment by jordalgo** [comment]
+1 to @ajor 's suggestion for making the config an enum of sorts

**Comment by viktormalik** [comment]
@jordalgo please check 8113d594ef3ce84afb9100173d14a60f3e7e7e55, it's a bit of hacky but I didn't come with another solution which wouldn't make the code too complicated. I used the same approach for the new config option.

**Review by ajor — APPROVED** [review]
It looks like the warnings / errors for kprobes are a different code path than for uprobes - would it make sense to add tests for the new config option with kprobes as well?

File: src/attached_probe.h [hunk 7]
```diff
@@ -23,13 +24,11 @@ class AttachedProbe {
   AttachedProbe(Probe &probe,
                 BpfProgram &&prog,
                 bool safe_mode,
-                BPFfeature &feature,
-                BTF &btf);
+                BPFtrace &bpftrace);
```
[the remark this answers is not in the document]
Comment (viktormalik) [reply src/attached_probe.h:27]: Yes, you just described my line of thought - I started with passing just `Config` and moving to `BPFtrace` once I realized that I need `is_traceable_func`, too.

**Comment by viktormalik** [comment]
> It looks like the warnings / errors for kprobes are a different code path than for uprobes - would it make sense to add tests for the new config option with kprobes as well?

Yes, good idea, added.

**Comment by viktormalik** [comment]
@jordalgo @danobi want to have a look once more after the latest changes?

Otherwise I'll go ahead, merge this, and craft the 0.21 release.

**Comment by jordalgo** [comment]
> @jordalgo please check https://github.com/bpftrace/bpftrace/commit/8113d594ef3ce84afb9100173d14a60f3e7e7e55, it's a bit of hacky but I didn't come with another solution which wouldn't make the code too complicated. I used the same approach for the new config option.

This is just to get the location in the code for the error output right? If so, that makes sense and doesn't seem too hacky.

File: man/adoc/bpftrace.adoc [hunk 8]
```diff
@@ -3427,6 +3427,22 @@ Default: 0
...
+=== missing_probes
+
+Default: `warn`
+
+Controls handling of probes with multiple kprobe or uprobe attach points which
+cannot be attached to some functions because they do not exist in the kernel or
+in the traced binary.
+
+The possible options are:
+- `error` - always fail on missing probes,
```
Comment (jordalgo) [inline man/adoc/bpftrace.adoc:3439]: nit: don't need commas at the end of these I think or a period at the end of the last one

File: man/adoc/bpftrace.adoc [hunk 9]
```diff
@@ -3427,6 +3427,22 @@ Default: 0
...
+- `warn` - print a warning but continue execution,
+- `ignore` - silently ignore missing probes.
+
+Warning: selecting the option `ignore` may result in probes not to be attached
```
Comment (jordalgo) [inline man/adoc/bpftrace.adoc:3443]: meh, I don't think this warning is necessary. I think people know what "ignore" means

**Review by jordalgo — COMMENTED** [review]
Few minor adoc nits. JC, do you want to make the config an env var as well like the others?

**Comment by ajor** [comment]
> Few minor adoc nits. JC, do you want to make the config an env var as well like the others?

I don't think we need to do that for every new config option. I see env vars as mainly being for backwards compatibility

**Comment by jordalgo** [comment]
> I don't think we need to do that for every new config option.

I will say that the one benefit is that they go into the `--help` output, which is nice - but maybe we should just add the config options instead of env vars to the help output.

File: man/adoc/bpftrace.adoc (hunk 8 above)
Comment (viktormalik) [reply man/adoc/bpftrace.adoc:3439]: Ah, that's my inner typography geek putting these in.

**Comment by viktormalik** [comment]
> > I don't think we need to do that for every new config option.

Agreed with @ajor here, no need to add more env vars.

> I will say that the one benefit is that they go into the `--help` output, which is nice - but maybe we should just add the config options instead of env vars to the help output.

Putting config options to help instead of env vars sounds good to me. Let's discuss in office hours.
