### PR TITLE
opaque value: handle unaligned accesses

### LINKED ISSUE #4644: UBSan: reference binding to misaligned address (..), which requires 8 byte alignment
### What reproduces the bug? Provide code if possible.

Building with UBSan (clang) found more undefined behaviour (misaligned addresses) in the following tests:

- AsyncActionTest.printf
- OpaqueValueTest.Concatenation
- OpaqueValueTest.ComplexTypeCombinations

For example:
```
[ RUN      ] AsyncActionTest.printf
/tmp/portage/dev-debug/bpftrace-0.24.9999/work/bpftrace-0.24.9999/src/util/opaque.h:150:12: runtime error: reference binding to misaligned address 0x55936f42786f for type 'const long', which requires 8 byte alignment
0x55936f42786f: note: pointer points here
 77 65 72 00 2a  00 00 00 00 00 00 00 ef  be ad de 00 00 00 00 61  00 00 00 00 00 00 00 00  21 00 00
             ^ 
    #0 0x559330523ef6 in long const& bpftrace::util::OpaqueValue::bitcast<long>(unsigned long) const (/tmp/portage/dev-debug/bpftrace-0.24.9999/work/bpftrace-0.24.9999_build/tests/bpftrace_test+0xc44ef6)
    #1 0x559330523bcb in long bpftrace::util::reduce_value<long>(bpftrace::util::OpaqueValue const&) (/tmp/portage/dev-debug/bpftrace-0.24.9999/work/bpftrace-0.24.9999_build/tests/bpftrace_test+0xc44bcb)
    #2 0x55933050c8ba in bpftrace::format(bpftrace::BPFtrace&, bpftrace::ast::CDefinitions const&, bpftrace::SizedType const&, bpftrace::util::OpaqueValue const&, unsigned int) (/tmp/portage/dev-debug/bpftrace-0.24.9999/work/bpftrace-0.24.9999_build/tests/bpftrace_test+0xc2d8ba)
```
(the other tests only differ in the data type of the reference)

This seems to be caused by the [custom bitcast implementation](https://github.com/bpftrace/bpftrace/blob/master/src/util/opaque.h#L147) which seems incorrect, as it simply returns a pointer as reference. The [reference documentation](https://en.cppreference.com/w/cpp/numeric/bit_cast.html) has an example implementation that copies the value.

### PR DESCRIPTION
**Pull request by amscanne**
Stacked PRs:
 * __->__#4651

--- --- ---

### opaque value: handle unaligned accesses

Since the types being bitcast will generally be small, it is more
efficient to simply return an instance of these types. This requires
that they are trivially copyable (which will be the case already).

Note that the `constexpr` if is not a premature optimization here; some
copied types lack a default constructor but *are* copyable. We still
require them to be trivially copyable (to avoid that set of footguns),
but allows these for objects that don't have alignment constraints.

Fixes #4644

Signed-off-by: Adin Scannell <amscanne@meta.com>

### CODE REVIEW

**Comment by hhoffstaette** [comment]
Looks good! Threw this into 0.24.x (where the literal folding fix just landed) together with the BUILD_UBSAN patch and:
```
[==========] 801 tests from 63 test suites ran. (68418 ms total)
[  PASSED  ] 801 tests.
```
:tada:

File: src/util/opaque.h [hunk 1]
```diff
@@ -144,10 +145,18 @@ class OpaqueValue {
...
 
   template <typename T>
-  const T &bitcast(size_t index = 0) const
+    requires(std::is_trivially_copyable_v<T>)
+  T bitcast(size_t index = 0) const
   {
     check(sizeof(T) * index, sizeof(T));
-    return reinterpret_cast<const T *>(data())[index];
+    const T *src = reinterpret_cast<const T *>(data()) + index;
+    if constexpr (std::alignment_of_v<T> <= 1) {
```
Comment (jordalgo) [inline src/util/opaque.h:158]: Just curious, do we have a lot of chars (or other types with 1 alignment) that pass through here? Also what types have 0 alignment?

**Review by jordalgo — APPROVED** [review]
Small question but otherwise LGTM

File: src/util/opaque.h (hunk 1 above)
Comment (amscanne) [reply src/util/opaque.h:158]: Yeah, the packed structs used for async events are alignment 1. They also don't have default constructors, so `AsyncEvent::buf x` is an error (but the copy here avoids that). That's really why I kept this, since I presume that `std::memcpy` has a reasonable fast path.

Re: `0`, I dunno. The spec requires that the alignment is a "nonnegative integer value" but also notes that the weakest alignment is `1`. What is the alignment for zero-sized types? I'm just playing it safe with my `<=`.

Edit: so the C++ standard *until C++20* was that there were no zero-sized types because each object requires a unique address. I could change my `<=` to `==` but,... I don't think it matters in practice.

Comment (jordalgo) [reply src/util/opaque.h:158]: > I don't think it matters in practice.

It doesn't but it matters a bit when reading the code as others may have the same question I did. Maybe just paste in part of your above comment.

Comment (amscanne) [reply src/util/opaque.h:158]: Fiiiiiine ;)
